[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#A100FF"
backgroundColor = "#f4f5f7"
secondaryBackgroundColor = "#ffffff"
textColor = "#1a1a2e"
font = "sans serif"
